### ISSUE TITLE
Keeping data anonymous

### ISSUE THREAD

**Issue by janedupuy** [marvinmarnold/stingraymappingproject.org#11]
B: "I’m a little puzzled about the data you will be able to collect from people who download the app and how you will use the data for research purposes.  Perhaps for my purposes – and less for the IRB – it may be worth articulating exactly what kind of information the app will glean from the users phone and how you are decoupling identifiable data from unidentifiable data.  That is, you are able to pick up their GPS location but you aren’t picking up their number or any other information off of the phone?  I don’t know anything about the back end interface of smartphones (I don’t even have one) but how can you guarantee you won’t pick up other information about the user or the use of the device?  Or, perhaps more importantly, how can you clearly demonstrate to the user that you won’t take other information?"

Me: Re: the data we’ll collect from participants’ phones, Marvin says that the IP address will be together with the data when it arrives, but he will have created no way of recording it so it will essentially disappear into the ether before it gets to us / the server. We’ll say on the app download page that we won’t be collecting any information beyond the threat level, time stamp, and GPS location, such that there will be no way to trace that information back to any individual user. We also say that in the consent form. Do you think that’s enough? 

Did I get that right? and are you down to put that information also on the app download page? I think it's a good idea in any case.

**Comment by janedupuy** [comment]
Also FYI, I figured out that GitHub just won't paste things from Word. If I paste text first into an e-mail and then copy it from there into this window, it comes through in the usual way.

**Comment by marvinmarnold** [comment]
Yup sounds good. We are also collecting version number. (It may sound nonmaterial, but each additional piece of info does help to deanonymize users).

It may also be helpful to stress that the code is open source. To the extent that other people get involved, there's oversight to make sure that this truly is all the info that is collected.

**Comment by janedupuy** [comment]
Great - I'll add both of those points to the proposal.

**Comment by marvinmarnold** [comment]
The simplest way to blur the GPS data that we share might just be to truncate it. According to [this](https://gis.stackexchange.com/questions/8650/how-to-measure-the-accuracy-of-latitude-and-longitude), 3 digits gives us 110m accuracy. What do you think about that?

**Comment by marvinmarnold** [comment]
For the moment, I'm using the 3 digit GPS to pull a city from google maps. I was hoping that I could make that happen client-side (no need to store in DB), but I have to do it server side (store to DB). I don't think this should cause any problems since the city is derived from the GPS which we were already storing.

**Comment by janedupuy** [comment]
How about two digit? Just for the public data, 110m is still sounding
pretty precise to me

**Comment by janedupuy** [comment]
I mean, how many meters would two digits be?

**Comment by marvinmarnold** [comment]
I can get down with that. There are still some prickly implementation details during the use case where we want to let users know if there are reported Stingrays near them even if they haven't personally detected it. We can either a) send their phone the list of recent TRUNCATED readings and live with the 1km error, or b) read their FULL GPS when they report, compare against recent readings and report back if a match.

a) is nice because we can do push notifications more easily and warn people in near real-time. b) is cool because we can do exact location coordinates. but we have to wait the 10min reporting period, and it leads to us doing more processing with user data. in an of itself, I think the processing is fine, but its probably a step in a bad direction.

**Comment by marvinmarnold** [comment]
2 digits is 1.1km

**Comment by marvinmarnold** [comment]
I'm going in circles about the coordinates. If we just truncate at 2 digits, then all the map points show up at the same place. To get around that, we could add random digits 3-5. But then it might be less clear that the points are approximations and could confuse users. Also, even if we have decided to not actively encourage users to physically track down Stingrays, this anonymization makes it impossible.

One final option would be to provide the full GPS coordinates for the most recent readings. This would only be sent to the map but there would be no technical way to prevent somebody from doing some stuff in the background to get the values in plaintext. The truncated coordinates would be provided when users download the data through our normal link.

**Comment by marvinmarnold** [comment]
Moved conversation to peerio
