### ISSUE TITLE
User training

### ISSUE THREAD

**Issue by janedupuy** [marvinmarnold/stingraymappingproject.org#6]
Should have started this as a thread, I realized:

So it sounds as though the 2G downgrade would indicate a more sustained connection with the Stingray? 

Also sounds as though for most users it may be much less important to turn off their phones than we thought - maybe the app will be picking up a nearly instantaneous connection that's already over by the time they get to their phones. Should we include this information on the website and/or app somehow? What do you think is the best way to fill people in ahead of time on what to expect / what they might do if their phones do alert them to a Stingray connection?

**Comment by marvinmarnold** [comment]
I didn't know what it meant. From http://www.wired.com/2015/03/feds-admit-stingrays-can-disrupt-cell-service-bystanders/

Although Scimeca disclosed to the magistrate that the equipment could disrupt phone service, he didn’t elaborate about how the disruption might occur. Experts suspect it has something to do with the “catch-and-release” way stingrays work. For example, once the stingray obtains the unique ID of a device, it releases it so that it can connect to a legitimate cell tower, allowing data and voice calls to go through.

“As each phone tries to connect, [the stingray] will say, ‘I’m really busy right now so go use a different tower. So rather than catching the phone, it will release it,” says Chris Soghoian, chief technologist for the ACLU. “The moment it tries to connect, [the stingray] can reject every single phone” that is not the target phone.

But the stingray may or may not release phones immediately, Soghoian notes, and during this period disruption can occur.

**Comment by janedupuy** [comment]
Marvin: Yup, the 2G downgrade establishes a sustained connection where it is technically possible to eavesdrop on calls and data but unknown to what extent this happens. The release method reveals that a certain phone was within range of the stingray at a specific time.

I think it could be useful knowledge for the Learn page. I think it may be confusing in the app. We can also get around this a little bit. We can have warnings that "your device is connected to a stingray" and that "a stingray has been detected nearby". You are right that barring radical picture taking militias, we are somewhat actionless in the former case. It can take up to an hour for a phone to connect to a nearby stingray so there is hope that we can prevent nearby phones from connecting if we warn them fast enough.

**Comment by marvinmarnold** [comment]
Moved conversation to peerio
